Revert "Add the REPORTING_ERROR_EVENT update engine state."
Right now we get the following error with LKGR of Chrome:
update_observer.cc: In member function 'virtual void chromeos::UpdateObserver::Changed(chromeos::UpdateLibrary*)':
update_observer.cc:26: error: enumeration value 'UPDATE_STATUS_REPORTING_ERROR_EVENT' not handled in switch

In order to fix this error, we need to update Chrome. Until we have a chance to
fix this, I'm rolling back this change so we can reopen the tree.

This reverts commit 80149acc23afacb66200ff22c928bc2cd98cd6b2.

Review URL: http://codereview.chromium.org/2873054